CREATE DATABASE UniD1oX

CREATE TABLE MSSTAFF(
STAFF_ID CHAR (5) CHECK (STAFF_ID LIKE 'SF[0-9][0-9][0-9]') PRIMARY KEY,
NAME VARCHAR (20) NOT NULL, 
PHONE_NUMBER VARCHAR (15) NOT NULL,
STAFF_ADDRESS VARCHAR (15) CHECK (LEN(STAFF_ADDRESS) <= 15 AND LEN(STAFF_ADDRESS) >= 10), 
AGE INT  NOT NULL, 
GENDER VARCHAR (6) CHECK (GENDER='MALE' OR GENDER='FEMALE'),
SALARY INT NOT NULL
);

CREATE TABLE MSMATERIAL (
MATERIAL_ID CHAR (5) CHECK (MATERIAL_ID LIKE 'MA[0-9][0-9][0-9]') PRIMARY KEY,
MATERIAL_NAME VARCHAR (20) NOT NULL,
MATERIAL_PRICE INT CHECK (MATERIAL_PRICE > 0),
QUANTITY INT NOT NULL
);

CREATE TABLE MSPURCHASE(
PURCHASETRANSACTION_ID CHAR (5) CHECK (PURCHASETRANSACTION_ID LIKE 'PU[0-9][0-9][0-9]') PRIMARY KEY,
STAFF_ID CHAR (5) FOREIGN KEY REFERENCES MSSTAFF(STAFF_ID) ON UPDATE CASCADE ON DELETE CASCADE,
SUPPLIER_ID CHAR (5) FOREIGN KEY REFERENCES MSSUPPLIER(SUPPLIER_ID) ON UPDATE CASCADE ON DELETE CASCADE,
TRANSACTION_DATE DATE NOT NULL,
PAYMENTTYPE_ID CHAR (5) FOREIGN KEY REFERENCES MSPAYMENTTYPE(PAYMENTTYPE_ID) ON UPDATE CASCADE ON DELETE CASCADE,
MATERIAL_ID CHAR (5) FOREIGN KEY REFERENCES MSMATERIAL(MATERIAL_ID) ON UPDATE CASCADE ON DELETE CASCADE,
PURCHASE_QUANTITY INT NOT NULL
);

CREATE TABLE MSSUPPLIER(
SUPPLIER_ID CHAR (5) CHECK (SUPPLIER_ID LIKE 'SU[0-9][0-9][0-9]') PRIMARY KEY,
SUPPLIER_NAME VARCHAR (20) CHECK (LEN(SUPPLIER_NAME) >= 6),
PHONE_NUMBER INT NOT NULL,
ADDRESS VARCHAR (15) NOT NULL
);

CREATE TABLE MSSALES(
TRANSACTIONSALES_ID CHAR (5) CHECK (TRANSACTIONSALES_ID LIKE 'SA[0-9][0-9][0-9]') PRIMARY KEY,
STAFF_ID CHAR (5) FOREIGN KEY REFERENCES MSSTAFF(STAFF_ID) ON UPDATE CASCADE ON DELETE CASCADE,
CUSTOMER_ID CHAR (5) FOREIGN KEY REFERENCES MSCUSTOMER(CUSTOMER_ID) ON UPDATE CASCADE ON DELETE CASCADE,
TRANSACTION_DATE DATE NOT NULL,
PAYMENTTYPE_ID CHAR (5) FOREIGN KEY REFERENCES MSPAYMENTTYPE(PAYMENTTYPE_ID) ON UPDATE CASCADE ON DELETE CASCADE,
CLOTH CHAR (5) FOREIGN KEY REFERENCES MSCLOTH(CLOTH_ID) ON UPDATE CASCADE ON DELETE CASCADE,
SALES_QUANTITY INT NOT NULL
);

CREATE TABLE MSCUSTOMER(
CUSTOMER_ID CHAR (5) CHECK (CUSTOMER_ID LIKE 'CU[0-9][0-9][0-9]') PRIMARY KEY,
NAME VARCHAR (20) NOT NULL, 
PHONE_NUMBER VARCHAR (15) NOT NULL,
ADDRESS VARCHAR (15) NOT NULL, 
GENDER VARCHAR (6) CHECK (GENDER='MALE' OR GENDER='FEMALE'),
EMAIL VARCHAR (50) CHECK (EMAIL LIKE '%@gmail.com' OR EMAIL LIKE '%@yahoo.com'),
DATE_OF_BIRTH DATE NOT NULL
); 

CREATE TABLE MSCLOTH(
CLOTH_ID CHAR (5) CHECK (CLOTH_ID LIKE 'CL[0-9][0-9][0-9]') PRIMARY KEY,
CLOTH_STOCK INT NOT NULL,
CONSTRAINT CK_MSCLOTH CHECK (CLOTH_STOCK >= 0 AND CLOTH_STOCK <= 250),
QUANTITY INT NOT NULL
);

CREATE Table MSPAYMENTTYPE (
PAYMENTTYPE_ID CHAR (5) CHECK (PAYMENTTYPE_ID LIKE 'PA[0-9][0-9][0-9]') PRIMARY KEY,
PAYMENT_TYPE VARCHAR (20) CHECK (PAYMENT_TYPE='DANA' OR PAYMENT_TYPE='OVO' OR PAYMENT_TYPE='Go-Pay' OR PAYMENT_TYPE='Shopee-Pay' OR PAYMENT_TYPE='Cash' OR PAYMENT_TYPE='Debit Card' 
OR PAYMENT_TYPE='Credit Card' OR PAYMENT_TYPE='Cryptocurrency' OR PAYMENT_TYPE='Flazz')
);

alter table MSCLOTH
drop column quantity
alter table MSCLOTH
add CLOTH_PRICE int not null

ALTER TABLE MSCUSTOMER
ALTER COLUMN ADDRESS varchar (50)

ALTER TABLE MSSUPPLIER
ALTER COLUMN ADDRESS varchar (50)

ALTER TABLE MSSUPPLIER
ALTER COLUMN PHONE_NUMBER varchar (20)


