CREATE DATABASE UNIDIOX

CREATE TABLE MSSTAFF(
STAFF_ID CHAR (5) CHECK (STAFF_ID LIKE 'SF[0-9][0-9][0-9]') PRIMARY KEY,
NAME VARCHAR (20) NOT NULL, 
PHONE_NUMBER VARCHAR (15) NOT NULL,
ADDRESS VARCHAR (15) NOT NULL, 
AGE INT  NOT NULL, 
GENDER VARCHAR (6) CHECK (GENDER='MALE' OR GENDER='FEMALE'),
SALARY INT NOT NULL
);

CREATE TABLE MSMATERIAL (
MATERIAL_ID CHAR (5) CHECK (MATERIAL_ID LIKE 'MA[0-9][0-9][0-9]') PRIMARY KEY,
MATERIAL_NAME VARCHAR (20),
QUANTITY INT
)

CREATE TABLE MSPURCHASE(
PURCHASETRANSACTION_ID CHAR (5) CHECK (PURCHASETRANSACTION_ID LIKE 'PA[0-9][0-9][0-9]') PRIMARY KEY,
STAFF_ID CHAR (5) FOREIGN KEY REFERENCES MSSTAFF(STAFF_ID) ON UPDATE CASCADE ON DELETE CASCADE,
SUPPLIER_ID CHAR (5) FOREIGN KEY REFERENCES MSSUPPLIER(SUPPLIER_ID) ON UPDATE CASCADE ON DELETE CASCADE,
TRANSACTION_DATE DATE NOT NULL,
PAYMENT_TYPE VARCHAR (10), 
MATERIAL_ID CHAR (5) FOREIGN KEY REFERENCES MSMATERIAL(MATERIAL_ID) ON UPDATE CASCADE ON DELETE CASCADE,
QUANTITY INT
);

CREATE TABLE MSSUPPLIER(
SUPPLIER_ID CHAR (5) CHECK (SUPPLIER_ID LIKE 'SU[0-9][0-9][0-9]') PRIMARY KEY,
SUPPLIER_NAME VARCHAR (20),
PHONE_NUMBER INT,
ADDRESS VARCHAR (15)
);

CREATE TABLE MSSALES(
TRANSACTIONSALES_ID CHAR (5) CHECK (TRANSACTIONSALES_ID LIKE 'SA[0-9][0-9][0-9]') PRIMARY KEY,
STAFF_ID CHAR (5) FOREIGN KEY REFERENCES MSSTAFF(STAFF_ID) ON UPDATE CASCADE ON DELETE CASCADE,
CUSTOMER_ID CHAR (5) FOREIGN KEY REFERENCES MSCUSTOMER(CUSTOMER_ID) ON UPDATE CASCADE ON DELETE CASCADE,
TRANSACTION_DATE DATE NOT NULL,
PAYMENT_TYPE VARCHAR (20) CHECK (PAYMENT_TYPE='DANA' OR PAYMENT_TYPE='OVO' OR PAYMENT_TYPE='Go-Pay' OR PAYMENT_TYPE='Shopee-Pay' OR PAYMENT_TYPE='Cash' OR PAYMENT_TYPE='Debit Card' 
OR PAYMENT_TYPE='Credit Card' OR PAYMENT_TYPE='Cryptocurrency' OR PAYMENT_TYPE='Flazz'),
CLOTH CHAR (5) FOREIGN KEY REFERENCES MSCLOTH(CLOTH_ID) ON UPDATE CASCADE ON DELETE CASCADE,
QUANTITY INT NOT NULL
)

CREATE TABLE MSCUSTOMER(
CUSTOMER_ID CHAR (5) CHECK (CUSTOMER_ID LIKE 'CU[0-9][0-9][0-9]') PRIMARY KEY,
NAME VARCHAR (20) NOT NULL, 
PHONE_NUMBER VARCHAR (15) NOT NULL,
ADDRESS VARCHAR (15) NOT NULL, 
GENDER VARCHAR (6) CHECK (GENDER='MALE' OR GENDER='FEMALE'),
EMAIL VARCHAR (15) NOT NULL,
DATE_OF_BIRTH DATE NOT NULL
) 

CREATE TABLE MSCLOTH(
CLOTH_ID CHAR (5) CHECK (CLOTH_ID LIKE 'CL[0-9][0-9][0-9]') PRIMARY KEY,
QUANTITY INT NOT NULL
)


